sudo: false
language: cpp
compiler: g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.7
    - g++-4.7
install:
  - sudo apt-get install -qq g++-4.7
  - export CXX="g++-4.7"
