sudo: false
language: cpp
compiler: g++-4.7
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.7
